# Generated by Django 3.2.6 on 2021-08-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210815_2322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Subject',
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='cls',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='cls',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='cls',
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(default='197c294f48b14484a4e7335c4659cf8d', on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='subject',
            field=models.ForeignKey(default='197c294f48b14484a4e7335c4659cf8d', on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(default='197c294f48b14484a4e7335c4659cf8d', on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='weekDay',
            field=models.CharField(choices=[('SEG', 'Segunda Feira'), ('TER', 'Terça Feira'), ('QUA', 'Quarta Feira'), ('QUI', 'Quinta Feira'), ('SEX', 'Sexta Feira')], max_length=15, verbose_name='Week day'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateField(verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='imageUrl',
            field=models.CharField(max_length=255, verbose_name='Image url'),
        ),
    ]
