# Generated by Django 3.2.6 on 2021-08-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210819_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-weekDay'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.URLField(default='https://zoom.us', max_length=255),
            preserve_default=False,
        ),
    ]
