# Generated by Django 3.2.6 on 2021-08-21 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210820_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='subject',
        ),
        migrations.AddField(
            model_name='notice',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Teacher'),
            preserve_default=False,
        ),
    ]
