# Generated by Django 3.2.6 on 2021-08-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_task_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
