# Generated by Django 3.2.6 on 2021-08-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210829_0341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
