# Generated by Django 3.2.6 on 2021-08-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_resource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachment',
            new_name='Resource',
        ),
    ]
